apiVersion: v1
kind: Pod
metadata:
  name: run-reporter-cis
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:<CALICO_VERSION>
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: <CIS_REPORT_NAME>
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #- name: TIGERA_COMPLIANCE_REPORT_START_TIME
    #  value: <report start time in UTC RFC3339 format, e.g.  2019-03-23T14:20:00Z>
    #- name: TIGERA_COMPLIANCE_REPORT_END_TIME
    #  value: <report start time in UTC RFC3339 format, e.g. 2019-03-23T15:10:00Z>
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      value: "<REPORT_START_TIME_UTC>"
    - name: TIGERA_COMPLIANCE_REPORT_END_TIME
      value: "<REPORT_END_TIME_UTC>"
      # By default reports get generated 30 min after the end of report time.
      # Modify this variable to change the default delay.
    - name: TIGERA_COMPLIANCE_JOB_START_DELAY
      value: "0m"
    - name: LOG_LEVEL
      value: "warning"
    # - name: ELASTIC_INDEX_SUFFIX
    #   value: cluster
    - name: ELASTIC_INDEX_SUFFIX
      value: <ELASTIC_INDEX_SUFFIX>
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/ssl/elastic/ca.pem
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
    resources: {}
  volumes:
  - name: var-log-calico 
    hostPath:
      path: /var/log/calico
      type: DirectoryOrCreate
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tls.crt
        path: ca.pem
      secretName: tigera-secure-es-gateway-http-certs-public
---
apiVersion: v1
kind: Pod
metadata:
  name: run-reporter-network-access
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:<CALICO_VERSION>
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: <NETWORK_ACCESS_REPORT_NAME>
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #- name: TIGERA_COMPLIANCE_REPORT_START_TIME
    #  value: <report start time in UTC RFC3339 format, e.g.  2019-03-23T14:20:00Z>
    #- name: TIGERA_COMPLIANCE_REPORT_END_TIME
    #  value: <report start time in UTC RFC3339 format, e.g. 2019-03-23T15:10:00Z>
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      value: "<REPORT_START_TIME_UTC>"
    - name: TIGERA_COMPLIANCE_REPORT_END_TIME
      value: "<REPORT_END_TIME_UTC>"
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # By default reports get generated 30 min after the end of report time.
      # Modify this variable to change the default delay.
    - name: TIGERA_COMPLIANCE_JOB_START_DELAY
      value: "0m"
    - name: LOG_LEVEL
      value: "warning"
    # - name: ELASTIC_INDEX_SUFFIX
    #   value: cluster
    - name: ELASTIC_INDEX_SUFFIX
      value: <ELASTIC_INDEX_SUFFIX>
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/ssl/elastic/ca.pem
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
    resources: {}
  volumes:
  - name: var-log-calico 
    hostPath:
      path: /var/log/calico
      type: DirectoryOrCreate
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tls.crt
        path: ca.pem
      secretName: tigera-secure-es-gateway-http-certs-public
---
apiVersion: v1
kind: Pod
metadata:
  name: run-reporter-inventory
  namespace: tigera-compliance
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccount: tigera-compliance-reporter
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: tigera-pull-secret
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:<CALICO_VERSION>
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify this value with name of an existing globalreport resource.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: <INVENTORY_REPORT_NAME>
      # Modify these values with the start and end time frame that should be reported on.
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #- name: TIGERA_COMPLIANCE_REPORT_START_TIME
    #  value: <report start time in UTC RFC3339 format, e.g.  2019-03-23T14:20:00Z>
    #- name: TIGERA_COMPLIANCE_REPORT_END_TIME
    #  value: <report start time in UTC RFC3339 format, e.g. 2019-03-23T15:10:00Z>
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      value: "<REPORT_START_TIME_UTC>"
    - name: TIGERA_COMPLIANCE_REPORT_END_TIME
      value: "<REPORT_END_TIME_UTC>"
      # By default reports get generated 30 min after the end of report time.
      # Modify this variable to change the default delay.
    - name: TIGERA_COMPLIANCE_JOB_START_DELAY
      value: "0m"
    - name: LOG_LEVEL
      value: "warning"
    # - name: ELASTIC_INDEX_SUFFIX
    #   value: cluster
    - name: ELASTIC_INDEX_SUFFIX
      value: <ELASTIC_INDEX_SUFFIX>
    - name: ELASTIC_SCHEME
      value: https
    - name: ELASTIC_HOST
      value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
    - name: ELASTIC_PORT
      value: "9200"
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: tigera-ee-compliance-reporter-elasticsearch-access
          key: password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      value: /etc/ssl/elastic/ca.pem
    volumeMounts:
    - mountPath: /var/log/calico
      name: var-log-calico
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
    resources: {}
  volumes:
  - name: var-log-calico 
    hostPath:
      path: /var/log/calico
      type: DirectoryOrCreate
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tls.crt
        path: ca.pem
      secretName: tigera-secure-es-gateway-http-certs-public
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: run-reporter-policy-audit
#   namespace: tigera-compliance
#   labels:
#     k8s-app: compliance-reporter
# spec:
#   nodeSelector:
#     kubernetes.io/os: linux
#   restartPolicy: Never
#   serviceAccount: tigera-compliance-reporter
#   serviceAccountName: tigera-compliance-reporter
#   tolerations:
#     - key: node-role.kubernetes.io/master
#       effect: NoSchedule
#   imagePullSecrets:
#     - name: tigera-pull-secret
#   containers:
#   - name: reporter
#     # Modify this image name, if you have re-tagged the image and are using a local
#     # docker image repository.
#     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     image: quay.io/tigera/compliance-reporter:<CALICO_VERSION>
#     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     env:
#       # Modify this value with name of an existing globalreport resource.
#       # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     - name: TIGERA_COMPLIANCE_REPORT_NAME
#       value: <POLICY_AUDIT_REPORT_NAME>
#       # Modify these values with the start and end time frame that should be reported on.
#       # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     #- name: TIGERA_COMPLIANCE_REPORT_START_TIME
#     #  value: <report start time in UTC RFC3339 format, e.g.  2019-03-23T14:20:00Z>
#     #- name: TIGERA_COMPLIANCE_REPORT_END_TIME
#     #  value: <report start time in UTC RFC3339 format, e.g. 2019-03-23T15:10:00Z>
#     - name: TIGERA_COMPLIANCE_REPORT_START_TIME
#       value: "<REPORT_START_TIME_UTC>"
#     - name: TIGERA_COMPLIANCE_REPORT_END_TIME
#       value: "<REPORT_END_TIME_UTC>"
#     # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#       # By default reports get generated 30 min after the end of report time.
#       # Modify this variable to change the default delay.
#     - name: TIGERA_COMPLIANCE_JOB_START_DELAY
#       value: "0m"
#     - name: LOG_LEVEL
#       value: "warning"
#     #- name: ELASTIC_INDEX_SUFFIX
#     #  value: cluster
#     - name: ELASTIC_INDEX_SUFFIX
#       value: <ELASTIC_INDEX_SUFFIX>
#     - name: ELASTIC_SCHEME
#       value: https
#     - name: ELASTIC_HOST
#       value: tigera-secure-es-gateway-http.tigera-elasticsearch.svc
#     - name: ELASTIC_PORT
#       value: "9200"
#     - name: ELASTIC_USER
#       valueFrom:
#         secretKeyRef:
#           name: tigera-ee-compliance-reporter-elasticsearch-access
#           key: username
#           optional: true
#     - name: ELASTIC_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: tigera-ee-compliance-reporter-elasticsearch-access
#           key: password
#           optional: true
#     - name: ELASTIC_SSL_VERIFY
#       value: "true"
#     - name: ELASTIC_CA
#       value: /etc/ssl/elastic/ca.pem
#     volumeMounts:
#     - mountPath: /var/log/calico
#       name: var-log-calico
#     - name: elastic-ca-cert-volume
#       mountPath: /etc/ssl/elastic/
#     livenessProbe:
#       httpGet:
#         path: /liveness
#         port: 9099
#         host: localhost
#     resources: {}
#   volumes:
#   - name: var-log-calico 
#     hostPath:
#       path: /var/log/calico
#       type: DirectoryOrCreate
#   - name: elastic-ca-cert-volume
#     secret:
#       optional: true
#       items:
#       - key: tls.crt
#         path: ca.pem
#       secretName: tigera-secure-es-gateway-http-certs-public
