apiVersion: projectcalico.org/v3
kind: PacketCapture
metadata:
  name: dev-capture-nginx
  namespace: dev
spec:
  selector: app == "nginx"
  filters:
  - protocol: TCP
    ports:
    - 80
  # if this field is skipped, the capture starts once the CR is deployed
  # startTime: "2021-08-26T12:00:00Z"
  
  # Mac terminal: date -v +30S -u +'%Y-%m-%dT%H:%M:%SZ'
  # Linux shell: date -u -d '30 sec' '+%Y-%m-%dT%H:%M:%SZ'
  # endTime: "2021-08-26T12:30:00Z"
  # endTime: "$END_TIME"